using CrestApps.OrchardCore.Omnichannel.Core;
using CrestApps.OrchardCore.Omnichannel.Messaging.Core.Channels;
using CrestApps.OrchardCore.Omnichannel.Messaging.Email.Models;

namespace CrestApps.OrchardCore.Omnichannel.Messaging.Email.Inbound;

/// <summary>
/// Keeps the workspace's automation silent on an email a machine wrote (an out-of-office, another system's
/// acknowledgement, bulk mail). The email is still recorded on the conversation, so an agent sees it; only the entry
/// point's auto-reply is held back, so two automatic replies cannot answer each other forever.
/// </summary>
public sealed class EmailAutomaticReplyInboundHandler : IMessagingInboundHandler
{
    /// <inheritdoc/>
    public int Order => 0;

    /// <inheritdoc/>
    public Task ReceivingAsync(MessagingInboundContext context, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(context);

        if (string.Equals(context.Channel.Name, OmnichannelConstants.Channels.Email, StringComparison.OrdinalIgnoreCase) &&
            context.Message.IsAutoGeneratedEmail())
        {
            context.SuppressAutomatedReplies = true;
        }

        return Task.CompletedTask;
    }

    /// <inheritdoc/>
    public Task ReceivedAsync(MessagingInboundContext context, CancellationToken cancellationToken = default)
        => Task.CompletedTask;
}
