namespace CrestApps.OrchardCore.Omnichannel.Messaging.Email.Inbound;

/// <summary>
/// Tells email a machine wrote (out-of-office and other automatic replies, bulk and list mail, bounces) from email a
/// person wrote, by the headers mail systems mark them with (RFC 3834 and the common vendor headers). Nothing automated
/// answers automatic mail, so an auto-reply and the customer's out-of-office cannot answer each other forever.
/// </summary>
public static class EmailAutoGeneratedDetector
{
    private static readonly string[] _automaticSenders = ["mailer-daemon@", "postmaster@"];

    /// <summary>
    /// Determines whether an email was written by a machine.
    /// </summary>
    /// <param name="email">The email.</param>
    /// <returns><see langword="true"/> when the email is automatic, bulk or a bounce.</returns>
    public static bool IsAutoGenerated(InboundEmail email)
    {
        ArgumentNullException.ThrowIfNull(email);

        if (email.DeliveryReport is not null)
        {
            return true;
        }

        if (email.Headers.TryGetValue("Auto-Submitted", out var autoSubmitted) &&
            !string.IsNullOrWhiteSpace(autoSubmitted) &&
            !autoSubmitted.Trim().StartsWith("no", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (email.Headers.TryGetValue("Precedence", out var precedence) &&
            precedence is not null &&
            (precedence.Contains("bulk", StringComparison.OrdinalIgnoreCase) ||
             precedence.Contains("junk", StringComparison.OrdinalIgnoreCase) ||
             precedence.Contains("list", StringComparison.OrdinalIgnoreCase) ||
             precedence.Contains("auto_reply", StringComparison.OrdinalIgnoreCase)))
        {
            return true;
        }

        if (email.Headers.ContainsKey("X-Autoreply") ||
            email.Headers.ContainsKey("X-Autorespond") ||
            email.Headers.ContainsKey("X-Autogenerated") ||
            email.Headers.ContainsKey("List-Id") ||
            email.Headers.ContainsKey("X-Failed-Recipients"))
        {
            return true;
        }

        // An empty return path ("<>") is how bounces and automatic notifications are sent.
        if (email.Headers.TryGetValue("Return-Path", out var returnPath) && returnPath?.Trim() == "<>")
        {
            return true;
        }

        var from = email.From?.Address;

        return from is not null && _automaticSenders.Any(sender => from.StartsWith(sender, StringComparison.OrdinalIgnoreCase));
    }
}
