using MimeKit;

namespace CrestApps.OrchardCore.Omnichannel.Messaging.Email.Inbound;

/// <summary>
/// Turns a raw RFC 822 message into an <see cref="InboundEmail"/>: the parser every source that has the message itself
/// shares (the mailbox reader, the raw MIME webhook, Amazon SES, SendGrid and Mailgun when they post the raw message).
/// </summary>
public static class MimeInboundEmailParser
{
    // The headers that say how and to whom an email was delivered, which name our address even when it was a Bcc or an
    // alias that forwarded to the mailbox.
    private static readonly string[] _deliveryHeaders = ["Delivered-To", "X-Original-To", "Envelope-To", "X-Envelope-To", "X-Forwarded-To"];

    // The headers the automatic-mail detector reads.
    private static readonly string[] _keptHeaders =
    [
        "Auto-Submitted",
        "Precedence",
        "X-Autoreply",
        "X-Autorespond",
        "X-Auto-Response-Suppress",
        "X-Autogenerated",
        "List-Id",
        "List-Unsubscribe",
        "Return-Path",
        "X-Failed-Recipients",
        "Feedback-ID",
    ];

    /// <summary>
    /// Parses a raw message.
    /// </summary>
    /// <param name="stream">The raw message.</param>
    /// <param name="cancellationToken">The token to monitor for cancellation requests.</param>
    /// <returns>The parsed email.</returns>
    public static async Task<InboundEmail> ParseAsync(Stream stream, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(stream);

        var message = await MimeMessage.LoadAsync(stream, cancellationToken);

        return Parse(message);
    }

    /// <summary>
    /// Parses a loaded message.
    /// </summary>
    /// <param name="message">The message.</param>
    /// <returns>The parsed email.</returns>
    public static InboundEmail Parse(MimeMessage message)
    {
        ArgumentNullException.ThrowIfNull(message);

        // A reply goes where the sender asked replies to go. A web form or a notification service sends from its own
        // address and names the customer in Reply-To; the customer is who the conversation is with.
        var sender = message.ReplyTo.Mailboxes.FirstOrDefault() ?? message.From.Mailboxes.FirstOrDefault() ?? message.Sender;
        var fromName = message.From.Mailboxes.FirstOrDefault()?.Name;

        var email = new InboundEmail
        {
            From = sender is null ? null : new InboundEmailAddress(sender.Address, string.IsNullOrWhiteSpace(sender.Name) ? fromName : sender.Name),
            To = message.To.Mailboxes.Select(ToAddress).Where(address => address.Address is not null).ToList(),
            Cc = message.Cc.Mailboxes.Select(ToAddress).Where(address => address.Address is not null).ToList(),
            Subject = message.Subject,
            TextBody = message.TextBody,
            HtmlBody = message.HtmlBody,
            MessageId = TrimMessageId(message.MessageId),
            InReplyTo = TrimMessageId(message.InReplyTo),
            References = message.References.Select(TrimMessageId).Where(reference => !string.IsNullOrEmpty(reference)).ToList(),
            Date = message.Date == DateTimeOffset.MinValue ? null : message.Date,
        };

        foreach (var header in _deliveryHeaders)
        {
            foreach (var value in message.Headers.Where(candidate => string.Equals(candidate.Field, header, StringComparison.OrdinalIgnoreCase)).Select(candidate => candidate.Value))
            {
                foreach (var address in ParseAddressList(value))
                {
                    email.DeliveredTo.Add(address);
                }
            }
        }

        foreach (var header in _keptHeaders)
        {
            var value = message.Headers[header];

            if (!string.IsNullOrWhiteSpace(value))
            {
                email.Headers[header] = value.Trim();
            }
        }

        foreach (var part in message.BodyParts)
        {
            switch (part)
            {
                case MessageDeliveryStatus status:
                    email.DeliveryReport ??= new InboundEmailDeliveryReport();
                    ReadDeliveryStatus(status, email.DeliveryReport);
                    break;

                case MessagePart attached when attached.Message is not null:
                    // The original message (or its headers) inside a bounce names the email that bounced. A message
                    // forwarded as an attachment is not kept as a file.
                    if (IsReport(message))
                    {
                        email.DeliveryReport ??= new InboundEmailDeliveryReport();
                        email.DeliveryReport.OriginalMessageId ??= TrimMessageId(attached.Message.MessageId);
                    }

                    break;

                case MimePart mimePart when IsFile(mimePart):
                    email.Attachments.Add(ToAttachment(mimePart));
                    break;
            }
        }

        return email;
    }

    /// <summary>
    /// Removes the angle brackets and white space around a <c>Message-ID</c>.
    /// </summary>
    /// <param name="messageId">The identifier as written.</param>
    /// <returns>The bare identifier, or <see langword="null"/> when it is empty.</returns>
    public static string TrimMessageId(string messageId)
    {
        if (string.IsNullOrWhiteSpace(messageId))
        {
            return null;
        }

        var trimmed = messageId.Trim().Trim('<', '>').Trim();

        return trimmed.Length == 0 ? null : trimmed;
    }

    /// <summary>
    /// Parses a list of identifiers as a <c>References</c> header writes them.
    /// </summary>
    /// <param name="value">The header value.</param>
    /// <returns>The bare identifiers, in order.</returns>
    public static IList<string> ParseMessageIds(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return [];
        }

        return value
            .Split([' ', '\t', '\r', '\n', ','], StringSplitOptions.RemoveEmptyEntries)
            .Select(TrimMessageId)
            .Where(id => !string.IsNullOrEmpty(id))
            .ToList();
    }

    /// <summary>
    /// Parses a list of addresses as an address header writes them.
    /// </summary>
    /// <param name="value">The header value.</param>
    /// <returns>The addresses, in their canonical form.</returns>
    public static IList<string> ParseAddressList(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return [];
        }

        if (InternetAddressList.TryParse(value, out var list))
        {
            return list.Mailboxes
                .Select(mailbox => new InboundEmailAddress(mailbox.Address).Address)
                .Where(address => address is not null)
                .ToList();
        }

        return value
            .Split([',', ';'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(candidate => new InboundEmailAddress(candidate).Address)
            .Where(address => address is not null)
            .ToList();
    }

    private static InboundEmailAddress ToAddress(MailboxAddress mailbox)
        => new(mailbox.Address, mailbox.Name);

    private static bool IsReport(MimeMessage message)
        => message.Body is MultipartReport ||
            message.BodyParts.Any(part => part is MessageDeliveryStatus);

    // A text part that is not marked as an attachment is the body; every other leaf part is a file.
    private static bool IsFile(MimePart part)
        => part.IsAttachment || part is not TextPart;

    private static InboundEmailAttachment ToAttachment(MimePart part)
    {
        using var buffer = new MemoryStream();

        part.Content?.DecodeTo(buffer);

        return new InboundEmailAttachment
        {
            FileName = part.FileName,
            ContentType = part.ContentType?.MimeType,
            Content = buffer.ToArray(),
            ContentId = TrimMessageId(part.ContentId),
            IsInline = part.ContentDisposition?.Disposition is { } disposition &&
                string.Equals(disposition, ContentDisposition.Inline, StringComparison.OrdinalIgnoreCase),
        };
    }

    private static void ReadDeliveryStatus(MessageDeliveryStatus status, InboundEmailDeliveryReport report)
    {
        // The first group is about the message; each following group is about one recipient.
        foreach (var group in status.StatusGroups.Skip(1))
        {
            report.Recipient ??= StripAddressType(group["Final-Recipient"] ?? group["Original-Recipient"]);
            report.Action ??= group["Action"]?.Trim();
            report.Status ??= group["Status"]?.Trim();
            report.Diagnostic ??= StripAddressType(group["Diagnostic-Code"]);
        }
    }

    // "rfc822; ann@example.com" names its address type first.
    private static string StripAddressType(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        var separator = value.IndexOf(';');

        return (separator >= 0 ? value.Substring(separator + 1) : value).Trim();
    }
}
