<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <Title>CrestApps OrchardCore Products</Title>
    <Description>
      $(OCCMSDescription)

      Module project for products.
    </Description>
    <PackageTags>$(PackageTags) CrestApps OrchardCoreCMS Products</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" />
    <PackageReference Include="OrchardCore.ContentManagement" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" />
    <PackageReference Include="OrchardCore.Deployment.Abstractions" />
    <PackageReference Include="OrchardCore.DisplayManagement" />
    <PackageReference Include="OrchardCore.Navigation.Core" />
    <PackageReference Include="OrchardCore.Recipes.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Abstractions\CrestApps.OrchardCore.Abstractions\CrestApps.OrchardCore.Abstractions.csproj" />
    <ProjectReference Include="..\..\Abstractions\CrestApps.OrchardCore.Taxation.Abstractions\CrestApps.OrchardCore.Taxation.Abstractions.csproj" />
    <ProjectReference Include="..\..\Core\CrestApps.OrchardCore.Core\CrestApps.OrchardCore.Core.csproj" />
    <ProjectReference Include="..\..\Core\CrestApps.OrchardCore.Products.Core\CrestApps.OrchardCore.Products.Core.csproj" />
    <ProjectReference Include="..\..\Core\CrestApps.OrchardCore.Recipes.Core\CrestApps.OrchardCore.Recipes.Core.csproj" />
    <ProjectReference Include="..\..\Core\CrestApps.OrchardCore.YesSql.Core\CrestApps.OrchardCore.YesSql.Core.csproj" />
  </ItemGroup>

</Project>
