<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>$(MSBuildProjectName)</RootNamespace>
    <Title>CrestApps OrchardCore Reports Contents Module</Title>
    <Description>
      $(CrestAppsDescription)

      Lets the CrestApps OrchardCore report designer use content types, such as customers or orders, as data sets.
    </Description>
    <PackageTags>$(PackageTags) Reports Contents</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.ContentManagement" />
    <PackageReference Include="OrchardCore.Contents.Core" />
    <PackageReference Include="OrchardCore.Module.Targets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Abstractions/CrestApps.OrchardCore.Abstractions/CrestApps.OrchardCore.Abstractions.csproj" />
    <ProjectReference Include="../../Abstractions/CrestApps.OrchardCore.Reports.Abstractions/CrestApps.OrchardCore.Reports.Abstractions.csproj" />
  </ItemGroup>

</Project>
