<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Abstractions",""))</RootNamespace>
    <Title>CrestApps OrchardCore Wizard Abstractions</Title>
    <Description>
      $(OCCMSDescription)

      Abstractions project for the reusable, multi-step wizard (stepper) framework.
    </Description>
    <PackageTags>$(PackageTags) CrestApps OrchardCoreCMS Wizard Stepper Abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.ContentManagement.Abstractions" />
    <PackageReference Include="OrchardCore.DisplayManagement" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrestApps.OrchardCore.Abstractions\CrestApps.OrchardCore.Abstractions.csproj" />
  </ItemGroup>

</Project>
