using CrestApps.OrchardCore.AI.Core;
using CrestApps.OrchardCore.Omnichannel.Automation;
using CrestApps.OrchardCore.Omnichannel.Core;
using CrestApps.OrchardCore.Omnichannel.Core.Models;
using CrestApps.OrchardCore.Omnichannel.Messaging.Core.Models;
using CrestApps.OrchardCore.Omnichannel.Messaging.Email;
using CrestApps.OrchardCore.Omnichannel.Messaging.Email.Models;
using OrchardCore.ContentManagement;

namespace CrestApps.OrchardCore.Omnichannel.Email.Services;

/// <summary>
/// The email channel as the automated conversation engine sees it. An email is answered after a short settle that gathers
/// several emails sent together into one reply, with no typing pause; automatic mail is never answered; a reply that only
/// asks to unsubscribe opts the contact out; and an opening message's first line <c>Subject: …</c> becomes its subject.
/// </summary>
internal sealed class EmailAutomatedMessagingChannel : IAutomatedMessagingChannel
{
    /// <summary>
    /// The shortest settle before an email is answered, so a customer who sends a correction a moment later gets one reply.
    /// </summary>
    internal static readonly TimeSpan MinimumSettle = TimeSpan.FromSeconds(15);

    /// <summary>
    /// The longest settle, whatever the configured reply delay says, so a reply always comes within minutes.
    /// </summary>
    internal static readonly TimeSpan MaximumSettle = TimeSpan.FromMinutes(5);

    private const string SubjectPrefix = "Subject:";

    // A reply that is nothing but one of these asks to stop receiving email.
    private static readonly HashSet<string> _optOutReplies = new(StringComparer.OrdinalIgnoreCase)
    {
        "unsubscribe",
        "unsubscribe me",
        "please unsubscribe me",
        "remove me",
        "please remove me",
        "remove me from your list",
        "opt out",
        "opt-out",
        "stop",
        "stop emailing me",
    };

    /// <inheritdoc/>
    public string Channel => EmailChannelConstants.ChannelName;

    /// <inheritdoc/>
    public string ReceivedEventType => OmnichannelConstants.Events.EmailReceived;

    /// <inheritdoc/>
    public ActivityKind ActivityKind => ActivityKind.Email;

    /// <inheritdoc/>
    public string UsageCategory => AIUsageCategories.Email;

    /// <inheritdoc/>
    public string ConclusionPromptTemplateId => "email-conclusion-analysis";

    /// <inheritdoc/>
    public string ConversationNoun => "email conversation";

    /// <inheritdoc/>
    public string NormalizeAddress(string address)
        => OmnichannelEmailAddress.Normalize(address);

    /// <inheritdoc/>
    public bool IsAutomaticMessage(OmnichannelMessage message)
        => message.IsAutoGeneratedEmail();

    /// <inheritdoc/>
    public bool IsOptOutRequest(OmnichannelMessage message, SubjectFlowSettings flowSettings)
    {
        ArgumentNullException.ThrowIfNull(message);

        var body = Clean(message.Content);
        var subject = Clean(message.GetSubject());

        return (!string.IsNullOrEmpty(body) && _optOutReplies.Contains(body)) ||
            (string.IsNullOrEmpty(body) && !string.IsNullOrEmpty(subject) && _optOutReplies.Contains(subject));
    }

    /// <inheritdoc/>
    public void ApplyOptOut(ContentItem contact, DateTime utcNow)
    {
        ArgumentNullException.ThrowIfNull(contact);

        contact.Alter<OmnichannelContactPart>(part => part.SetDoNotEmail(true, utcNow));
    }

    /// <inheritdoc/>
    public TimeSpan? GetDefaultResponseDelay(SubjectFlowSettings flowSettings)
        => null;

    /// <inheritdoc/>
    public TimeSpan GetReadingDelay(TimeSpan? configuredDelay, int pendingCharacters)
    {
        var delay = configuredDelay ?? MinimumSettle;

        if (delay < MinimumSettle)
        {
            delay = MinimumSettle;
        }

        return delay > MaximumSettle ? MaximumSettle : delay;
    }

    /// <inheritdoc/>
    public TimeSpan GetTypingDelay(int replyCharacters)
        => TimeSpan.Zero;

    /// <inheritdoc/>
    public (string Subject, string Body) SplitOpeningMessage(string renderedMessage)
    {
        if (string.IsNullOrWhiteSpace(renderedMessage))
        {
            return (null, renderedMessage);
        }

        var text = renderedMessage.Replace("\r\n", "\n", StringComparison.Ordinal).TrimStart();
        var lineEnd = text.IndexOf('\n');
        var firstLine = lineEnd >= 0 ? text.Substring(0, lineEnd) : text;

        if (!firstLine.StartsWith(SubjectPrefix, StringComparison.OrdinalIgnoreCase))
        {
            return (null, renderedMessage.Trim());
        }

        var subject = firstLine.Substring(SubjectPrefix.Length).Trim();
        var body = lineEnd >= 0 ? text.Substring(lineEnd + 1).Trim() : string.Empty;

        return (string.IsNullOrEmpty(subject) ? null : subject, body);
    }

    private static string Clean(string text)
        => text?.Trim().TrimEnd('.', '!').Trim();
}
