<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CrestApps.OrchardCore.DncRegistry</RootNamespace>
    <Title>CrestApps OrchardCore DNC Registry Abstractions</Title>
    <Description>
      $(CrestAppsDescription)

      Abstractions for the CrestApps OrchardCore DNC Registry module.
    </Description>
    <PackageTags>$(PackageTags) DncRegistry Abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Transitions\CrestApps.Core.PhoneNumbers.Abstractions\CrestApps.Core.PhoneNumbers.Abstractions.csproj" />
  </ItemGroup>

</Project>
