[default]
exten => _X.,1,NoOp(CrestApps Asterisk local test call to ${EXTEN})
 same => n,Answer()
 same => n,Wait(1)
 same => n,PlayTones(440/250,0/100,523/250,0/100,659/500)
 same => n,Wait(2)
 same => n,StopPlayTones()
 same => n,Echo()
 same => n,Hangup()

exten => _+X.,1,NoOp(CrestApps Asterisk local test call to ${EXTEN})
 same => n,Answer()
 same => n,Wait(1)
 same => n,PlayTones(440/250,0/100,523/250,0/100,659/500)
 same => n,Wait(2)
 same => n,StopPlayTones()
 same => n,Echo()
 same => n,Hangup()
