<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Abstractions",""))</RootNamespace>
    <Title>CrestApps OrchardCore Addresses Abstractions</Title>
    <Description>
      $(OCCMSDescription)

      Provider-agnostic abstractions for representing postal and geographic addresses across the platform.
    </Description>
    <PackageTags>$(PackageTags) CrestApps OrchardCoreCMS Addresses Abstractions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CrestApps.Core.Abstractions" />
  </ItemGroup>

</Project>
