using CrestApps.OrchardCore.Models;
using Microsoft.Extensions.AI;

namespace CrestApps.OrchardCore.AI.Models;

/// <summary>
/// Represents a prompt/message in a chat interaction stored as a separate document.
/// This allows for better performance with large chat histories by avoiding
/// document contention and reducing the size of the main ChatInteraction document.
/// </summary>
public sealed class ChatInteractionPrompt : CatalogItem
{
    /// <summary>
    /// Gets or sets the ChatInteractionId this prompt belongs to.
    /// </summary>
    public string ChatInteractionId { get; set; }

    /// <summary>
    /// Gets or sets the role of the message sender (user, assistant, system).
    /// </summary>
    public ChatRole Role { get; set; }

    /// <summary>
    /// Gets or sets the text content of the prompt/message.
    /// </summary>
    public string Text { get; set; }

    /// <summary>
    /// Gets or sets the title of the prompt (if any).
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this prompt was auto-generated by the system.
    /// </summary>
    public bool IsGeneratedPrompt { get; set; }

    /// <summary>
    /// Gets or sets the references (citations) in this prompt.
    /// </summary>
    public Dictionary<string, AICompletionReference> References { get; set; }

    /// <summary>
    /// Gets or sets the UTC date and time when the prompt was created.
    /// </summary>
    public DateTime CreatedUtc { get; set; }
}
