using CrestApps.OrchardCore.Omnichannel.Core.Models;
using OrchardCore.Entities;

namespace CrestApps.OrchardCore.Omnichannel.Messaging.Email.Models;

/// <summary>
/// Reads the <see cref="EmailMessageMetadata"/> kept on a message's property bag.
/// </summary>
public static class EmailMessageMetadataExtensions
{
    /// <summary>
    /// Gets the email metadata of a message.
    /// </summary>
    /// <param name="message">The message.</param>
    /// <returns>The metadata, or <see langword="null"/> when the message carries none (it was not an email).</returns>
    public static EmailMessageMetadata GetEmailMetadata(this OmnichannelMessage message)
    {
        ArgumentNullException.ThrowIfNull(message);

        return message.TryGet<EmailMessageMetadata>(out var metadata)
            ? metadata
            : null;
    }

    /// <summary>
    /// Determines whether a message is an email a machine wrote, which nothing automated answers.
    /// </summary>
    /// <param name="message">The message.</param>
    /// <returns><see langword="true"/> when the message is an automatic or bulk email.</returns>
    public static bool IsAutoGeneratedEmail(this OmnichannelMessage message)
        => message?.GetEmailMetadata()?.IsAutoGenerated == true;
}
