namespace CrestApps.OrchardCore.Omnichannel.Messaging.Email.Models;

/// <summary>
/// What an email carries beyond its subject and body, kept on the message's property bag: the identifiers mail clients
/// thread by, the other people copied, and whether a machine rather than a person wrote it.
/// </summary>
public sealed class EmailMessageMetadata
{
    /// <summary>
    /// Gets or sets the email's <c>Message-ID</c>, without the angle brackets.
    /// </summary>
    public string MessageId { get; set; }

    /// <summary>
    /// Gets or sets the <c>Message-ID</c> of the email this one answers (its <c>In-Reply-To</c>), without the angle
    /// brackets.
    /// </summary>
    public string InReplyTo { get; set; }

    /// <summary>
    /// Gets or sets the <c>Message-ID</c>s of the thread this email belongs to (its <c>References</c>), oldest first.
    /// </summary>
    public IList<string> References { get; set; } = [];

    /// <summary>
    /// Gets or sets the display name the sender wrote under, such as <c>Ann Lee</c>.
    /// </summary>
    public string FromName { get; set; }

    /// <summary>
    /// Gets or sets the other addresses the email was sent to or copied to.
    /// </summary>
    public IList<string> Cc { get; set; } = [];

    /// <summary>
    /// Gets or sets a value indicating whether the email was written by a machine: an out-of-office or other automatic
    /// reply, or bulk mail. Nothing automated answers it, so two systems cannot reply to each other forever.
    /// </summary>
    public bool IsAutoGenerated { get; set; }
}
