using System.ComponentModel.DataAnnotations;
using CrestApps.Core;
using CrestApps.Core.AI.Models;
using CrestApps.Core.Models;
using CrestApps.OrchardCore.Omnichannel.Automation;
using CrestApps.OrchardCore.Omnichannel.Core;
using CrestApps.OrchardCore.Omnichannel.Core.Models;
using CrestApps.OrchardCore.Omnichannel.Email.Services;
using CrestApps.OrchardCore.Omnichannel.Messaging.Core.Models;
using CrestApps.OrchardCore.Omnichannel.Messaging.Email;
using CrestApps.OrchardCore.Omnichannel.Messaging.Email.Mailbox;
using CrestApps.OrchardCore.Omnichannel.Messaging.Email.Models;
using CrestApps.OrchardCore.Omnichannel.Messaging.Email.Services;
using CrestApps.OrchardCore.Tests.Telephony.Doubles;
using Microsoft.Extensions.AI;
using OrchardCore.ContentManagement;
using OrchardCore.Entities;

namespace CrestApps.OrchardCore.Tests.Omnichannel.Messaging.Email;

public sealed class EmailAutomationTests
{
    [Fact]
    public void SplitOpeningMessage_AFirstLineSubject_BecomesTheSubject()
    {
        // Arrange
        var channel = new EmailAutomatedMessagingChannel();

        // Act
        var (subject, body) = channel.SplitOpeningMessage("Subject: Thanks for your interest\nHi Ann,\n\nCould you tell me more?");

        // Assert
        Assert.Equal("Thanks for your interest", subject);
        Assert.Equal("Hi Ann,\n\nCould you tell me more?", body);
    }

    [Fact]
    public void SplitOpeningMessage_WithoutASubjectLine_KeepsTheWholeMessageAsTheBody()
    {
        // Arrange
        var channel = new EmailAutomatedMessagingChannel();

        // Act
        var (subject, body) = channel.SplitOpeningMessage("Hi Ann, thanks for reaching out.");

        // Assert
        Assert.Null(subject);
        Assert.Equal("Hi Ann, thanks for reaching out.", body);
    }

    [Theory]
    [InlineData("Unsubscribe", null, true)]
    [InlineData("unsubscribe.", null, true)]
    [InlineData("Remove me", null, true)]
    [InlineData("", "Unsubscribe", true)]
    [InlineData("Please unsubscribe my colleague and keep me on.", null, false)]
    [InlineData("What does unsubscribe do?", null, false)]
    public void IsOptOutRequest_OnlyAReplyThatIsNothingButARequestToStop(string body, string subject, bool expected)
    {
        // Arrange
        var channel = new EmailAutomatedMessagingChannel();
        var message = new OmnichannelMessage { Content = body };

        message.SetSubject(subject);

        // Act & Assert
        Assert.Equal(expected, channel.IsOptOutRequest(message, flowSettings: null));
    }

    [Fact]
    public void IsAutomaticMessage_AnOutOfOfficeReply_IsNeverAnswered()
    {
        // Arrange
        var channel = new EmailAutomatedMessagingChannel();
        var message = new OmnichannelMessage();

        message.Put(new EmailMessageMetadata { IsAutoGenerated = true });

        // Act & Assert
        Assert.True(channel.IsAutomaticMessage(message));
        Assert.False(channel.IsAutomaticMessage(new OmnichannelMessage()));
    }

    [Fact]
    public void ApplyOptOut_MarksTheContactDoNotEmail()
    {
        // Arrange
        var channel = new EmailAutomatedMessagingChannel();
        var contact = new ContentItem { ContentType = "Contact" };
        var now = new DateTime(2026, 10, 9, 12, 0, 0, DateTimeKind.Utc);

        // Act
        channel.ApplyOptOut(contact, now);

        // Assert
        Assert.True(contact.TryGet<OmnichannelContactPart>(out var part));
        Assert.True(part.DoNotEmail);
        Assert.Equal(now, part.DoNotEmailUtc);
    }

    [Theory]
    [InlineData(null, 15)]
    [InlineData(5, 15)]
    [InlineData(60, 60)]
    [InlineData(3600, 300)]
    public void GetReadingDelay_SettlesBrieflyAndNeverWaitsTooLong(int? configuredSeconds, int expectedSeconds)
    {
        // Arrange
        var channel = new EmailAutomatedMessagingChannel();
        var configured = configuredSeconds.HasValue ? TimeSpan.FromSeconds(configuredSeconds.Value) : (TimeSpan?)null;

        // Act & Assert
        Assert.Equal(TimeSpan.FromSeconds(expectedSeconds), channel.GetReadingDelay(configured, pendingCharacters: 500));
        Assert.Equal(TimeSpan.Zero, channel.GetTypingDelay(500));
    }

    [Fact]
    public void GetTrailingUserMessages_IsWhatTheCustomerSentSinceTheLastReply()
    {
        // Arrange
        var transcript = new List<AIChatSessionPrompt>
        {
            new() { Role = ChatRole.Assistant, Content = "Opening" },
            new() { Role = ChatRole.User, Content = "First" },
            new() { Role = ChatRole.Assistant, Content = "Reply" },
            new() { Role = ChatRole.User, Content = "Second" },
            new() { Role = ChatRole.User, Content = "Third" },
        };

        // Act
        var pending = AutomatedConversationTranscript.GetTrailingUserMessages(transcript);

        // Assert
        Assert.Equal(["Second", "Third"], pending.Select(prompt => prompt.Content));
        Assert.Empty(AutomatedConversationTranscript.GetTrailingUserMessages(transcript.Take(3).ToList()));
    }

    [Fact]
    public void Build_CarriesTheProviderMessageIdOfEveryCustomerTurnSoTheHumanThreadDoesNotImportItTwice()
    {
        // Arrange
        var message = new OmnichannelMessage { Content = "Hi", ProviderMessageId = "CAF1@mail.example.com" };
        var prompt = AutomatedConversationTranscript.CreateCustomerPrompt("session-1", message, DateTime.UtcNow);

        // Act
        var transcript = AutomatedConversationTranscript.Build([prompt]);

        // Assert
        var entry = Assert.Single(transcript);
        Assert.True(entry.IsInbound);
        Assert.Equal("CAF1@mail.example.com", entry.ProviderMessageId);
        Assert.Equal(prompt.ItemId, entry.Id);
    }

    [Theory]
    [InlineData(0, null, true)]
    [InlineData(1, 1, false)]
    [InlineData(1, 3, true)]
    [InlineData(3, 7, false)]
    [InlineData(3, 9, true)]
    [InlineData(20, 59, false)]
    [InlineData(20, 61, true)]
    public void IsDue_AFailingMailboxIsTriedLessAndLessOften(int failures, int? minutesSinceFailure, bool expected)
    {
        // Arrange
        var now = new DateTime(2026, 10, 9, 12, 0, 0, DateTimeKind.Utc);
        var state = new EmailMailboxSyncState
        {
            ConsecutiveFailures = failures,
            LastFailedUtc = minutesSinceFailure.HasValue ? now.AddMinutes(-minutesSinceFailure.Value) : null,
        };

        // Act & Assert
        Assert.Equal(expected, EmailMailboxPoller.IsDue(state, now));
    }

    [Fact]
    public async Task AddressRule_RefusesSettingsThatCannotWork()
    {
        // Arrange
        var rule = new EmailAddressSettingsRule(new PassThroughStringLocalizer<EmailAddressSettingsRule>());
        var address = new OmnichannelChannelEndpoint { Capabilities = [OmnichannelConstants.Channels.Email] };

        address.Put(new EmailAddressSettings
        {
            TransportName = EmailChannelConstants.Transports.Smtp,
            InboundMode = EmailInboundMode.Mailbox,
            Mailbox = new EmailMailboxSettings { AfterProcessing = EmailMailboxAfterProcessing.MoveToFolder },
        });

        var context = new ValidatingContext<OmnichannelChannelEndpoint>(address);

        // Act
        await rule.ValidateAsync(context, TestContext.Current.CancellationToken);

        // Assert
        Assert.False(context.Result.Succeeded);
        Assert.Equal(3, context.Result.Errors.Count);
        Assert.Contains(context.Result.Errors, error => error.MemberNames.Contains("SmtpHost"));
        Assert.Contains(context.Result.Errors, error => error.MemberNames.Contains("ImapHost"));
        Assert.Contains(context.Result.Errors, error => error.MemberNames.Contains("ProcessedFolder"));
    }

    [Fact]
    public async Task AddressRule_IgnoresAnAddressThatIsNotUsedForEmail()
    {
        // Arrange
        var rule = new EmailAddressSettingsRule(new PassThroughStringLocalizer<EmailAddressSettingsRule>());
        var address = new OmnichannelChannelEndpoint { Capabilities = [OmnichannelConstants.Channels.Phone] };

        address.Put(new EmailAddressSettings { TransportName = EmailChannelConstants.Transports.Smtp });

        var context = new ValidatingContext<OmnichannelChannelEndpoint>(address);

        // Act
        await rule.ValidateAsync(context, TestContext.Current.CancellationToken);

        // Assert
        Assert.True(context.Result.Succeeded);
    }
}
