using CrestApps.OrchardCore.Omnichannel.Messaging.Email.Inbound;

namespace CrestApps.OrchardCore.Tests.Omnichannel.Messaging.Email;

public sealed class EmailAutoGeneratedDetectorTests
{
    [Theory]
    [InlineData("Auto-Submitted", "auto-replied")]
    [InlineData("Auto-Submitted", "auto-generated")]
    [InlineData("Precedence", "bulk")]
    [InlineData("Precedence", "junk")]
    [InlineData("Precedence", "list")]
    [InlineData("X-Autoreply", "yes")]
    [InlineData("X-Autorespond", "yes")]
    [InlineData("List-Id", "<news.example.com>")]
    [InlineData("Return-Path", "<>")]
    public void IsAutoGenerated_RecognisesTheHeadersAutomaticMailIsMarkedWith(string header, string value)
    {
        // Arrange
        var email = PersonalEmail();
        email.Headers[header] = value;

        // Act & Assert
        Assert.True(EmailAutoGeneratedDetector.IsAutoGenerated(email));
    }

    [Fact]
    public void IsAutoGenerated_AutoSubmittedNo_IsAPersonsEmail()
    {
        // Arrange
        var email = PersonalEmail();
        email.Headers["Auto-Submitted"] = "no";

        // Act & Assert
        Assert.False(EmailAutoGeneratedDetector.IsAutoGenerated(email));
    }

    [Theory]
    [InlineData("mailer-daemon@contoso.com")]
    [InlineData("postmaster@example.com")]
    public void IsAutoGenerated_MailFromAMailSystem_IsAutomatic(string from)
    {
        // Arrange
        var email = PersonalEmail();
        email.From = new InboundEmailAddress(from);

        // Act & Assert
        Assert.True(EmailAutoGeneratedDetector.IsAutoGenerated(email));
    }

    [Fact]
    public void IsAutoGenerated_ABounce_IsAutomatic()
    {
        // Arrange
        var email = PersonalEmail();
        email.DeliveryReport = new InboundEmailDeliveryReport { Action = "failed" };

        // Act & Assert
        Assert.True(EmailAutoGeneratedDetector.IsAutoGenerated(email));
    }

    [Fact]
    public void IsAutoGenerated_APersonsEmail_IsNot()
    {
        // Act & Assert
        Assert.False(EmailAutoGeneratedDetector.IsAutoGenerated(PersonalEmail()));
    }

    private static InboundEmail PersonalEmail()
        => new()
        {
            From = new InboundEmailAddress("ann@example.com", "Ann"),
            Subject = "Question",
            TextBody = "Hello",
        };
}
