using System.Text.Json;
using CrestApps.OrchardCore.Omnichannel.Core;
using CrestApps.OrchardCore.Omnichannel.Core.Models;
using CrestApps.OrchardCore.Omnichannel.Core.Services;
using CrestApps.OrchardCore.Omnichannel.Messaging.Core.Models;
using CrestApps.OrchardCore.Omnichannel.Messaging.Email.Inbound;
using CrestApps.OrchardCore.Omnichannel.Messaging.Email.Models;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using OrchardCore.Entities;
using YesSql;

namespace CrestApps.OrchardCore.Tests.Omnichannel.Messaging.Email;

public sealed class EmailInboundInboxHandlerTests
{
    [Fact]
    public async Task HandleAsync_ARedeliveredEmail_SavesUnderTheSameIdentityAndRaisesTheSameEventBothTimes()
    {
        // Arrange
        // The durable inbox absorbs a redelivered email by its Message-ID, and the handler must hand the same work to the
        // same guarded path on a replay: the same message identity and the same event id, so the workspace and the AI
        // recognise the second delivery rather than recording or answering it twice.
        var saved = new List<OmnichannelMessage>();
        var session = new Mock<ISession>();

        session
            .Setup(value => value.SaveAsync(It.IsAny<OmnichannelMessage>(), It.IsAny<bool>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask)
            .Callback<object, bool, string, CancellationToken>((message, _, _, _) => saved.Add((OmnichannelMessage)message));

        var eventHandler = new RecordingOmnichannelEventHandler();
        var handler = new EmailInboundInboxHandler([eventHandler], session.Object, NullLogger<EmailInboundInboxHandler>.Instance);

        var message = new OmnichannelMessage
        {
            Id = "msg-1",
            ProviderMessageId = "CAF1@mail.example.com",
            Channel = OmnichannelConstants.Channels.Email,
            Content = "Where is my order?",
            CustomerAddress = "ann@example.com",
            ServiceAddress = "support@contoso.com",
            IsInbound = true,
        };

        message.SetSubject("Order 1042");
        message.Put(new EmailMessageMetadata { MessageId = "CAF1@mail.example.com", FromName = "Ann Lee" });

        var payload = JsonSerializer.Serialize(message);

        // Act
        await handler.HandleAsync(payload, TestContext.Current.CancellationToken);
        await handler.HandleAsync(payload, TestContext.Current.CancellationToken);

        // Assert
        Assert.Equal(2, saved.Count);
        Assert.Equal(saved[0].Id, saved[1].Id);
        Assert.Equal(2, eventHandler.Events.Count);
        Assert.All(eventHandler.Events, evt => Assert.Equal(OmnichannelConstants.Events.EmailReceived, evt.EventType));
        Assert.Equal("CAF1@mail.example.com", eventHandler.Events[0].Id);
        Assert.Equal(eventHandler.Events[0].Id, eventHandler.Events[1].Id);
    }

    [Fact]
    public async Task HandleAsync_KeepsTheSubjectAndEmailMetadataThroughThePayload()
    {
        // Arrange
        var eventHandler = new RecordingOmnichannelEventHandler();
        var handler = new EmailInboundInboxHandler([eventHandler], Mock.Of<ISession>(), NullLogger<EmailInboundInboxHandler>.Instance);

        var message = new OmnichannelMessage
        {
            Id = "msg-2",
            ProviderMessageId = "abc@example.com",
            Channel = OmnichannelConstants.Channels.Email,
            Content = "Hello",
            IsInbound = true,
        };

        message.SetSubject("Question");
        message.SetQuotedText("> earlier");
        message.Put(new EmailMessageMetadata { MessageId = "abc@example.com", InReplyTo = "root@contoso.com", IsAutoGenerated = true });

        // Act
        await handler.HandleAsync(JsonSerializer.Serialize(message), TestContext.Current.CancellationToken);

        // Assert
        var received = Assert.Single(eventHandler.Events).Message;

        Assert.Equal("Question", received.GetSubject());
        Assert.Equal("> earlier", received.GetQuotedText());
        Assert.Equal("root@contoso.com", received.GetEmailMetadata().InReplyTo);
        Assert.True(received.IsAutoGeneratedEmail());
    }

    [Fact]
    public async Task HandleAsync_RefusesAPayloadItCannotRead()
    {
        // Arrange
        var handler = new EmailInboundInboxHandler([], Mock.Of<ISession>(), NullLogger<EmailInboundInboxHandler>.Instance);

        // Act & Assert
        await Assert.ThrowsAnyAsync<Exception>(() => handler.HandleAsync("null", TestContext.Current.CancellationToken));
    }

    private sealed class RecordingOmnichannelEventHandler : IOmnichannelEventHandler
    {
        public List<OmnichannelEvent> Events { get; } = [];

        public Task HandleAsync(OmnichannelEvent omnichannelEvent, CancellationToken cancellationToken = default)
        {
            Events.Add(omnichannelEvent);

            return Task.CompletedTask;
        }
    }
}
