# To create a new minor workflow, increment the verion in the following name and in env.version

name: Create a release

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'src/docs/**/*'
    tags: 
      - 'v*.*.*'
env:
  companyName: 'crestapps' # must have a lowercase value
  projectName: 'dealersolutions' # must have a lowercase value
  appName: 'elasticdealer'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Get the version
      id: get_version
      run: |
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        VERSION="${VERSION//v}"
        echo VERSION:${VERSION}
        echo ::set-output name=VERSION::${VERSION}
      shell: bash
    - uses: actions/checkout@v3
      with:
         ref: main
         
    - name: Docker Setup Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3   
      
    - name: Azure Container Registry Login 
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_CLOUDSOLUTIONS_HOST }}
        username: ${{ secrets.ACR_CLOUDSOLUTIONS_USERNAME }}
        password: ${{ secrets.ACR_CLOUDSOLUTIONS_PASSWORD }}
    
    - name: Build and push Docker images
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        file: ./Dockerfile
        tags: ${{ secrets.ACR_CLOUDSOLUTIONS_HOST }}/${{ env.companyName }}/${{ env.projectName }}:${{ steps.get_version.outputs.VERSION }}
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Deploy to prodution
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ env.appName }}'
        publish-profile: ${{ secrets.AZURE_ELASTICDEALER_PRODUCTION_PUBLISH_PROFILE }}
        images: "${{ secrets.ACR_CLOUDSOLUTIONS_HOST }}/${{ env.companyName }}/${{ env.projectName }}:${{ steps.get_version.outputs.VERSION }}"
