<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>CrestApps OrchardCore Taxation Core</Title>
    <Description>
      $(OCCMSDescription)

      Core services and default implementations for the CrestApps taxation framework.
    </Description>
    <PackageTags>$(PackageTags) CrestApps OrchardCoreCMS Taxation</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CrestApps.OrchardCore.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CrestApps.Core" />
    <PackageReference Include="OrchardCore.Infrastructure.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Abstractions/CrestApps.OrchardCore.Taxation.Abstractions/CrestApps.OrchardCore.Taxation.Abstractions.csproj" />
    <ProjectReference Include="../CrestApps.OrchardCore.Core/CrestApps.OrchardCore.Core.csproj" />
  </ItemGroup>

</Project>
